"""Transpiler from Capa to Python 3.12+.

Strategy: walk the AST after semantic analysis, emitting Python code
line by line through an ``Emitter`` that handles indentation automatically.
The output is intended to be executed by a Python 3.10 or later
interpreter (for match/case).

Main mappings:

- Functions and methods: Python ``def`` without type annotations (simpler
  and avoids issues with generic types / capabilities whose exact
  signature does not always have an equivalent in ``typing``).
- ``let`` and ``var``: indistinguishable in Python, both emit ``x = expr``.
  The immutability of ``let`` was verified statically by the analyzer.
- ``type T { ... }`` (struct): ``@dataclass`` with the fields.
- ``type T = A | B(P) | ...`` (sum): each variant is a class. For
  variants with a payload, it is a dataclass with a single ``value`` field.
  The type name becomes a union (not emitted, Capa does not need it at
  runtime, and Python does not require it).
- ``trait``: abstract ABC with abstract methods (informative). The impls
  generate concrete subclasses.
- ``impl T``: methods added as class functions.
- ``impl Trait for T``: class T inherits from the corresponding trait.
- ``match``: Python ``match/case``.
- ``?`` (try): local expansion with ``if isinstance(_t, Err): return _t``.
- Strings with ``${expr}``: translated to f-strings; ``$$`` escapes ``$``.
- Constant variants (``Red``): call ``Red()`` (instance).
- Capabilities and types imported from the runtime stdlib: a single
  ``from capa.runtime import *`` is emitted at the top of the generated file.

Known limitations (v1):

- No optimizations: the output is reasonably readable but is not
  "idiomatic Python", it is Python that closely mirrors the Capa
  structure.
- No tail call detection.
- ``self`` in methods is translated directly; Capa "self" and Python
  "self" align naturally.
- The ``?`` operator requires the enclosing function to return ``Result``.
  If it does not, the generated code will produce an early return of an
  Err, useful as a runtime diagnostic, but not detected at transpilation
  time in v1.
"""

from __future__ import annotations

import re
from typing import Optional

from . import capa_ast as A
from .typesys import Ty, TyName


# ===========================================================
# Header of the generated file
# ===========================================================

_PRELUDE = '''\
# Generated by capa transpiler. Do not edit by hand.
# Generated from: {filename}

from __future__ import annotations
from dataclasses import dataclass, field
from capa.runtime import (
    Ok, Err, Result, Some, None_, Option, IoError,
    Stdio, Fs, Env, Clock, Random, Net, Proc, Db, Unsafe,
    CapaList, _NoneType,
    parse_int, parse_float,
    to_float, to_int,
    py_import, py_invoke,
    JNull, JBool, JNum, JStr, JArr, JObj, JsonValue,
    parse_json, to_json,
)
'''


class TranspilerError(Exception):
    """Transpiler error (an unsupported transpilation case)."""
    pass


# ===========================================================
# Emitter: handles indentation and lines
# ===========================================================


class Emitter:
    """Accumulator of output lines with automatic indentation."""

    def __init__(self, indent_unit: str = "    "):
        self.lines: list[str] = []
        self._indent = 0
        self._unit = indent_unit

    def write(self, line: str) -> None:
        if line == "":
            self.lines.append("")
        else:
            self.lines.append(self._unit * self._indent + line)

    def blank(self) -> None:
        # Only add a blank line if the last one is not already blank.
        if self.lines and self.lines[-1] != "":
            self.lines.append("")

    def indent(self) -> None:
        self._indent += 1

    def dedent(self) -> None:
        self._indent -= 1
        assert self._indent >= 0

    def get(self) -> str:
        # Ensures the file ends with a newline and has no trailing
        # blank lines.
        text = "\n".join(self.lines).rstrip() + "\n"
        return text


# ===========================================================
# Transpiler
# ===========================================================


# Capa operators -> Python (most are the same, a few need mapping).
_BINOP_MAP = {
    "+": "+",
    "-": "-",
    "*": "*",
    "/": "/",
    "%": "%",
    "==": "==",
    "!=": "!=",
    "<": "<",
    "<=": "<=",
    ">": ">",
    ">=": ">=",
    "and": "and",
    "or": "or",
}

_UNARY_MAP = {
    "-": "-",
    "not": "not ",  # space - `not` is a word
}


# Reserved Python identifiers (relevant subset to avoid collisions
# with Capa names when we emit Python).
_PY_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}


def _safe_ident(name: str) -> str:
    """Suffix names that collide with Python keywords."""
    if name in _PY_KEYWORDS:
        return name + "_"
    return name


class Transpiler:
    """Transpiles a Capa AST to Python 3.10+.

    Can optionally receive ``types`` (mapping ``id(expr) -> Ty``)
    from AnalyzeResult, which allows emitting more precise code for
    method calls on specific types (e.g., String, List).
    """

    def __init__(
        self,
        filename: str = "<input>",
        types: Optional[dict[int, Ty]] = None,
    ):
        self.filename = filename
        self.em = Emitter()
        # Counter for unique temporary names (e.g., for `?`).
        self._tmp_counter = 0
        # Stack for "are we inside a function that can propagate errors?".
        # Not used for checking (that is the checker's job), but to
        # generate good code for ?.
        self._fun_stack: list[str] = []
        # Type mapping from the analyzer (optional, but needed for
        # type-aware dispatch in method calls - e.g., String methods
        # that must map to distinct Python functions).
        self.types: dict[int, Ty] = types or {}

    def transpile(self, module: A.Module) -> str:
        self.em.lines.append(_PRELUDE.format(filename=self.filename).rstrip())
        self.em.blank()

        # First pass: handle all imports, top-level consts and type decls.
        for item in module.items:
            self._emit_item(item)
            self.em.blank()

        # Detect if there is a `main` and generate the bootstrap.
        main_decl = next(
            (
                it for it in module.items
                if isinstance(it, A.FunDecl) and it.name == "main"
            ),
            None,
        )
        if main_decl is not None:
            self._emit_main_bootstrap(main_decl)

        return self.em.get()

    # ===========================================================
    # Top-level items
    # ===========================================================

    def _emit_item(self, item: A.Item) -> None:
        if isinstance(item, A.Import):
            self._emit_import(item)
        elif isinstance(item, A.ConstDecl):
            self._emit_const(item)
        elif isinstance(item, A.TypeStruct):
            self._emit_struct(item)
        elif isinstance(item, A.TypeSum):
            self._emit_sum(item)
        elif isinstance(item, A.TraitDecl):
            self._emit_trait(item)
        elif isinstance(item, A.ImplBlock):
            self._emit_impl(item)
        elif isinstance(item, A.FunDecl):
            self._emit_fun(item)
        else:
            raise TranspilerError(f"unsupported top-level item: {type(item).__name__}")

    def _emit_import(self, imp: A.Import) -> None:
        # Defense in depth: the analyzer rejects `import` in v1, so in
        # complete pipelines this function is never called with a valid
        # module. If we get here (e.g., direct transpilation without
        # going through the analyzer), we emit only a comment, *never*
        # a Python `import` - that would be the hole the analyzer is
        # closing.
        path = ".".join(imp.path)
        alias = f" as {imp.alias}" if imp.alias else ""
        self.em.write(
            f"# capa: 'import {path}{alias}' rejected, "
            f"use py_import(unsafe, ...) instead"
        )

    def _emit_const(self, c: A.ConstDecl) -> None:
        value_code = self._emit_expr(c.value)
        self.em.write(f"{c.name} = {value_code}")

    def _emit_struct(self, t: A.TypeStruct) -> None:
        self.em.write("@dataclass")
        if t.fields:
            self.em.write(f"class {t.name}:")
            self.em.indent()
            for fld in t.fields:
                self.em.write(f"{_safe_ident(fld.name)}: object")
            self.em.dedent()
        else:
            self.em.write(f"class {t.name}:")
            self.em.indent()
            self.em.write("pass")
            self.em.dedent()

    def _emit_sum(self, t: A.TypeSum) -> None:
        # For each variant: a class.
        # - Without payload: empty class, instantiated as Variant().
        # - With payload: dataclass with `value` field.
        for v in t.variants:
            if v.payload is None:
                self.em.write(f"class {v.name}:")
                self.em.indent()
                self.em.write("pass")
                self.em.dedent()
            else:
                self.em.write("@dataclass")
                self.em.write(f"class {v.name}:")
                self.em.indent()
                self.em.write("value: object")
                self.em.dedent()
            self.em.blank()
        # Type alias for the sum type. Useful in type hints, optional at runtime.
        if t.variants:
            union = " | ".join(v.name for v in t.variants)
            self.em.write(f"{t.name} = {union}")

    def _emit_trait(self, t: A.TraitDecl) -> None:
        # Generate a Protocol-like: simple class without implementation. The
        # impls that register this trait inherit from `_Trait_<Name>`. The
        # method is only declared (with `...`).
        self.em.write(f"class _Trait_{t.name}:")
        self.em.indent()
        if not t.methods:
            self.em.write("pass")
        else:
            for m in t.methods:
                params = ", ".join(_safe_ident(p.name) for p in m.params)
                self.em.write(f"def {_safe_ident(m.name)}({params}):")
                self.em.indent()
                self.em.write("raise NotImplementedError")
                self.em.dedent()
        self.em.dedent()
        # Alias for use in annotations (not used at runtime).
        self.em.write(f"{t.name} = _Trait_{t.name}")

    def _emit_impl(self, impl: A.ImplBlock) -> None:
        # In Python, methods are added directly to the target class.
        # For trait impls, we could optionally inject the inheritance,
        # but that would involve modifying the existing declaration.
        # Instead, we just add the methods. The trait/impl relationship
        # is semantic in Capa and statically checked - at runtime, it
        # is enough that the methods exist.
        target = impl.type_name
        for m in impl.methods:
            params = ", ".join(_safe_ident(p.name) for p in m.params)
            if _uses_try(m.body):
                self.em.write("@_capa_wrap")
            self.em.write(f"def _{target}_{m.name}({params}):")
            self.em.indent()
            self._emit_block_body(m.body)
            self.em.dedent()
            self.em.write(f"{target}.{_safe_ident(m.name)} = _{target}_{m.name}")
            self.em.blank()

    def _emit_fun(self, fn: A.FunDecl) -> None:
        params = ", ".join(_safe_ident(p.name) for p in fn.params)
        self._fun_stack.append(fn.name)
        # If the function uses `?`, it needs the decorator that catches
        # the internal exception used for propagation.
        if _uses_try(fn.body):
            self.em.write("@_capa_wrap")
        self.em.write(f"def {_safe_ident(fn.name)}({params}):")
        self.em.indent()
        self._emit_block_body(fn.body)
        self.em.dedent()
        self._fun_stack.pop()

    def _emit_main_bootstrap(self, main_decl: A.FunDecl) -> None:
        """Generates the ``if __name__ == "__main__":`` block that
        instantiates capabilities and calls ``main(...)``."""
        self.em.blank()
        self.em.write('if __name__ == "__main__":')
        self.em.indent()
        # Resolve each parameter to a capability instance.
        args = []
        for p in main_decl.params:
            cap_name = self._capability_for_param(p)
            args.append(f"{cap_name}()")
        if args:
            self.em.write(f"main({', '.join(args)})")
        else:
            self.em.write("main()")
        self.em.dedent()

    def _capability_for_param(self, p: A.Param) -> str:
        """Returns the name of the capability class that parameterizes
        ``p``, based on the type annotation."""
        te = p.type_expr
        if isinstance(te, A.TypeName):
            return te.name
        # Fallback - we assume Stdio just so something happens.
        return "Stdio"

    # ===========================================================
    # Block and statements
    # ===========================================================

    def _emit_block_body(self, block: A.Block) -> None:
        if not block.stmts:
            self.em.write("pass")
            return
        for stmt in block.stmts:
            self._emit_stmt(stmt)

    def _emit_stmt(self, s: A.Stmt) -> None:
        if isinstance(s, A.LetStmt):
            self._emit_let(s)
        elif isinstance(s, A.VarStmt):
            value = self._emit_expr(s.value)
            self.em.write(f"{_safe_ident(s.name)} = {value}")
        elif isinstance(s, A.AssignStmt):
            target = self._emit_expr(s.target)
            value = self._emit_expr(s.value)
            self.em.write(f"{target} {s.op} {value}")
        elif isinstance(s, A.IfStmt):
            self._emit_if(s)
        elif isinstance(s, A.WhileStmt):
            self._emit_while(s)
        elif isinstance(s, A.ForStmt):
            self._emit_for(s)
        elif isinstance(s, A.ReturnStmt):
            if s.value is None:
                self.em.write("return")
            else:
                self.em.write(f"return {self._emit_expr(s.value)}")
        elif isinstance(s, A.BreakStmt):
            self.em.write("break")
        elif isinstance(s, A.ContinueStmt):
            self.em.write("continue")
        elif isinstance(s, A.ExprStmt):
            # Special case: ExprStmt(MatchExpr) emits match/case directly
            # without needing a temporary variable - the value is discarded.
            if isinstance(s.expr, A.MatchExpr):
                self._emit_match_stmt(s.expr)
            else:
                self.em.write(self._emit_expr(s.expr))
        else:
            raise TranspilerError(f"unsupported statement: {type(s).__name__}")

    def _emit_match_stmt(self, m: A.MatchExpr) -> None:
        """Emits a MatchExpr whose value is discarded (used as a statement).

        Each arm body emits its statements directly - without capturing
        the value in a temporary.
        """
        scrut = self._emit_expr(m.scrutinee)
        self.em.write(f"match {scrut}:")
        self.em.indent()
        for arm in m.arms:
            pat = self._emit_pattern_match(arm.pattern)
            if arm.guard is not None:
                guard = self._emit_expr(arm.guard)
                self.em.write(f"case {pat} if {guard}:")
            else:
                self.em.write(f"case {pat}:")
            self.em.indent()
            if isinstance(arm.body, A.Block):
                self._emit_block_body(arm.body)
            else:
                # Body is a single expression used as a statement: emit
                # as a line that evaluates the expression and discards it.
                self.em.write(self._emit_expr(arm.body))
            self.em.dedent()
        self.em.dedent()

    def _emit_let(self, s: A.LetStmt) -> None:
        value = self._emit_expr(s.value)
        target = self._emit_pattern_lvalue(s.pattern)
        self.em.write(f"{target} = {value}")

    def _emit_pattern_lvalue(self, p: A.Pattern) -> str:
        """Emits a pattern as an assignment target (let/for).

        For simple patterns (Wildcard, Ident), returns the name or ``_``
        directly. Tuples are supported: ``(a, b)`` in Capa becomes
        ``(a, b)`` in Python, valid as an assignment target.
        More complex patterns are not supported in let/for.
        """
        if isinstance(p, A.WildcardPat):
            return "_"
        if isinstance(p, A.IdentPat):
            return _safe_ident(p.name)
        if isinstance(p, A.TuplePat):
            if not p.elements:
                # () as assignment target: ignore the value (let the
                # right-hand side evaluate to Unit).
                return "_"
            subs = [self._emit_pattern_lvalue(sub) for sub in p.elements]
            if len(subs) == 1:
                return f"({subs[0]},)"
            return f"({', '.join(subs)})"
        raise TranspilerError(
            f"complex pattern in let/for not yet supported: {type(p).__name__}"
        )

    def _emit_if(self, s: A.IfStmt) -> None:
        self.em.write(f"if {self._emit_expr(s.cond)}:")
        self.em.indent()
        self._emit_block_body(s.then_block)
        self.em.dedent()
        for cond, blk in s.elif_arms:
            self.em.write(f"elif {self._emit_expr(cond)}:")
            self.em.indent()
            self._emit_block_body(blk)
            self.em.dedent()
        if s.else_block is not None:
            self.em.write("else:")
            self.em.indent()
            self._emit_block_body(s.else_block)
            self.em.dedent()

    def _emit_while(self, s: A.WhileStmt) -> None:
        self.em.write(f"while {self._emit_expr(s.cond)}:")
        self.em.indent()
        self._emit_block_body(s.body)
        self.em.dedent()

    def _emit_for(self, s: A.ForStmt) -> None:
        target = self._emit_pattern_lvalue(s.pattern)
        iter_code = self._emit_expr(s.iter)
        self.em.write(f"for {target} in {iter_code}:")
        self.em.indent()
        self._emit_block_body(s.body)
        self.em.dedent()

    def _emit_pattern_match(self, p: A.Pattern) -> str:
        """Emits a pattern for use inside a Python ``case``."""
        if isinstance(p, A.WildcardPat):
            return "_"
        if isinstance(p, A.IdentPat):
            # In Python, a bare name in a case is a binding.
            return _safe_ident(p.name)
        if isinstance(p, A.LiteralPat):
            return self._emit_expr(p.value)
        if isinstance(p, A.VariantPat):
            # Special case: Option's None is a singleton (None_) at
            # runtime, an instance of _NoneType. Python match requires
            # a class - we use _NoneType().
            if p.name == "None":
                if p.payload is not None:
                    raise TranspilerError("'None' takes no payload")
                return "_NoneType()"
            if p.payload is None:
                return f"{p.name}()"
            sub = self._emit_pattern_match(p.payload)
            return f"{p.name}({sub})"
        if isinstance(p, A.StructPat):
            parts = []
            for fname, fpat in p.fields:
                if fpat is None:
                    parts.append(f"{_safe_ident(fname)}={_safe_ident(fname)}")
                else:
                    parts.append(f"{_safe_ident(fname)}={self._emit_pattern_match(fpat)}")
            return f"{p.type_name}({', '.join(parts)})"
        if isinstance(p, A.TuplePat):
            # () in Python match is not valid as a pattern - use _.
            # But an empty Capa tuple = Unit, and a Unit scrutinee is rare
            # in match. For other sizes, emit (p1, p2, ...).
            if not p.elements:
                return "()"
            subs = [self._emit_pattern_match(sub) for sub in p.elements]
            if len(subs) == 1:
                return f"({subs[0]},)"
            return f"({', '.join(subs)})"
        if isinstance(p, A.OrPat):
            # Python match accepts ``a | b | c`` directly.
            alts = [self._emit_pattern_match(a) for a in p.alternatives]
            return " | ".join(alts)
        raise TranspilerError(f"unsupported pattern in match: {type(p).__name__}")

    # ===========================================================
    # Expressions
    # ===========================================================

    def _emit_expr(self, e: A.Expr) -> str:
        if isinstance(e, A.IntLit):
            return repr(e.value)
        if isinstance(e, A.FloatLit):
            return repr(e.value)
        if isinstance(e, A.StringLit):
            return self._emit_string_lit(e.value)
        if isinstance(e, A.InterpolatedString):
            return self._emit_interpolated_string(e)
        if isinstance(e, A.CharLit):
            # Capa Char -> length-1 str in Python (Python has no char).
            return repr(e.value)
        if isinstance(e, A.BoolLit):
            return "True" if e.value else "False"
        if isinstance(e, A.UnitLit):
            return "None"
        if isinstance(e, A.Ident):
            return self._emit_ident(e.name)
        if isinstance(e, A.BinOp):
            l = self._emit_expr(e.left)
            r = self._emit_expr(e.right)
            op = _BINOP_MAP.get(e.op)
            if op is None:
                raise TranspilerError(f"unsupported binop: {e.op}")
            return f"({l} {op} {r})"
        if isinstance(e, A.UnaryOp):
            op = _UNARY_MAP.get(e.op)
            if op is None:
                raise TranspilerError(f"unsupported unary: {e.op}")
            inner = self._emit_expr(e.operand)
            return f"({op}{inner})"
        if isinstance(e, A.Call):
            return self._emit_call(e)
        if isinstance(e, A.MethodCall):
            return self._emit_method_call(e)
        if isinstance(e, A.FieldAccess):
            recv = self._emit_expr(e.receiver)
            return f"{recv}.{_safe_ident(e.field_name)}"
        if isinstance(e, A.Index):
            recv = self._emit_expr(e.receiver)
            idx = self._emit_expr(e.index)
            return f"{recv}[{idx}]"
        if isinstance(e, A.Try):
            return self._emit_try(e)
        if isinstance(e, A.StructLit):
            parts = []
            for fname, fexpr in e.fields:
                parts.append(f"{_safe_ident(fname)}={self._emit_expr(fexpr)}")
            return f"{e.type_name}({', '.join(parts)})"
        if isinstance(e, A.ListLit):
            els = ", ".join(self._emit_expr(x) for x in e.elements)
            return f"CapaList([{els}])"
        if isinstance(e, A.TupleLit):
            if not e.elements:
                return "()"
            if len(e.elements) == 1:
                return f"({self._emit_expr(e.elements[0])},)"
            els = ", ".join(self._emit_expr(x) for x in e.elements)
            return f"({els})"
        if isinstance(e, A.MatchExpr):
            return self._emit_match_expr(e)
        if isinstance(e, A.IfExpr):
            cond = self._emit_expr(e.cond)
            then_e = self._emit_expr(e.then_expr)
            else_e = self._emit_expr(e.else_expr)
            return f"({then_e} if {cond} else {else_e})"
        if isinstance(e, A.LambdaExpr):
            return self._emit_lambda(e)
        if isinstance(e, A.RangeExpr):
            start = self._emit_expr(e.start)
            end = self._emit_expr(e.end)
            # `a..=b` is inclusive; Python's range stops one before the
            # second argument, so we add 1. Wrap the result in CapaList
            # so all List methods (length, map, filter, fold, ...)
            # transparently apply.
            stop = f"({end}) + 1" if e.inclusive else end
            return f"CapaList(range({start}, {stop}))"
        raise TranspilerError(f"unsupported expression: {type(e).__name__}")

    def _emit_lambda(self, e: A.LambdaExpr) -> str:
        """Emits a lambda as Python.

        - Single-expr body: ``(lambda x: body)`` (a Python expression).
        - Block body: generates a nested function with a unique name
          before the current line (hoisting), and returns that name.
          The Emitter is already in statement-producing mode, and the
          nested function's stmts appear at the correct indentation
          level.
        """
        if isinstance(e.body, A.Block):
            name = f"_lambda_{self._tmp_counter}"
            self._tmp_counter += 1
            params = ", ".join(_safe_ident(p.name) for p in e.params)
            self.em.write(f"def {name}({params}):")
            self.em.indent()
            self._emit_block_body(e.body)
            self.em.dedent()
            return name
        param_names = ", ".join(_safe_ident(p.name) for p in e.params)
        body = self._emit_expr(e.body)
        return f"(lambda {param_names}: {body})"

    def _emit_match_expr(self, m: A.MatchExpr) -> str:
        """Emits a MatchExpr used in expression position.

        Strategy: generates a Python match/case that assigns to a
        temporary variable, and returns the variable's name. The
        match/case lines are emitted to the Emitter *before* the current
        line (because they are prelude to the statement the caller is
        building).

        Caveat: this does not work if the caller has already emitted
        part of the current line. In the current design, ``_emit_expr``
        is always called *before* ``em.write`` for the statement where
        it appears, so the prelude lands in the right place.

        For an arm body that is an expression, the expression's value
        is the match's value. For a block body, we assign None to the
        temporary - the caller is responsible for using ``return``
        inside the block if it wants to exit with a different value.
        """
        tmp = f"_m{self._tmp_counter}"
        self._tmp_counter += 1
        scrut = self._emit_expr(m.scrutinee)
        self.em.write(f"match {scrut}:")
        self.em.indent()
        for arm in m.arms:
            pat = self._emit_pattern_match(arm.pattern)
            if arm.guard is not None:
                guard = self._emit_expr(arm.guard)
                self.em.write(f"case {pat} if {guard}:")
            else:
                self.em.write(f"case {pat}:")
            self.em.indent()
            if isinstance(arm.body, A.Block):
                # For v1, blocks as arm body in expression context
                # produce None. If the user wants a concrete value,
                # they must use a single-line expr or an explicit return.
                self._emit_block_body(arm.body)
                self.em.write(f"{tmp} = None")
            else:
                body_code = self._emit_expr(arm.body)
                self.em.write(f"{tmp} = {body_code}")
            self.em.dedent()
        self.em.dedent()
        return tmp

    def _emit_ident(self, name: str) -> str:
        # Constant variants (PascalCase, no calls after) are
        # instantiated. This is already handled by the fact that emit of
        # Call/MethodCall produces `{name}(...)` separately. Here we only
        # emit the bare name; if it is a payload-less variant used as a
        # value (e.g., `return Red`), it needs to become `Red()`.
        # Special case: ``None`` is a runtime singleton, not an
        # instantiable class. Map it directly to the ``None_`` singleton.
        if name == "None":
            return "None_"
        if name and name[0].isupper() and name not in (
            # Capabilities, Result variants, Option variants - these are
            # not "simple variants" because they are classes that must
            # be explicitly instantiated (and usually already are via Call).
        ):
            # Heuristic: if it is a bare Ident with a PascalCase name,
            # it is probably a variant being used as a value - emit it
            # as `Name()`. Cases that need the raw type (e.g., passing
            # a class) are rare in Capa.
            return f"{name}()"
        return _safe_ident(name)

    def _emit_method_call(self, e: A.MethodCall) -> str:
        """Emits a method call. For receivers of types with a built-in
        method API (String, Map, Set), maps to Python constructs. For
        other types (CapaList, user structs), emits a direct Python
        method call.
        """
        recv = self._emit_expr(e.receiver)
        args_code = [self._emit_expr(a) for a in e.args]

        # Type-aware dispatch. Built-in method maps (String, Map, Set)
        # see only positional arguments because the analyzer rejects
        # named arguments on builtins.
        recv_ty = self.types.get(id(e.receiver))
        if isinstance(recv_ty, TyName):
            if recv_ty.name == "String":
                return self._emit_string_method(e.method, recv, args_code)
            if recv_ty.name == "Map":
                return self._emit_map_method(e.method, recv, args_code)
            if recv_ty.name == "Set":
                return self._emit_set_method(e.method, recv, args_code)

        # User-defined methods: respect named arguments.
        args = self._emit_call_arg_list(e.args, e.arg_names)
        return f"{recv}.{_safe_ident(e.method)}({args})"

    def _emit_string_method(
        self, method: str, recv: str, args: list[str],
    ) -> str:
        """Maps a Capa String method to the equivalent Python construct."""
        if method == "length":
            return f"len({recv})"
        if method == "contains":
            return f"({args[0]} in {recv})"
        if method == "starts_with":
            return f"{recv}.startswith({args[0]})"
        if method == "ends_with":
            return f"{recv}.endswith({args[0]})"
        if method == "to_upper":
            return f"{recv}.upper()"
        if method == "to_lower":
            return f"{recv}.lower()"
        if method == "trim":
            return f"{recv}.strip()"
        if method == "split":
            return f"CapaList({recv}.split({args[0]}))"
        if method == "replace":
            return f"{recv}.replace({args[0]}, {args[1]})"
        if method == "is_empty":
            return f"({recv} == '')"
        return f"{recv}.{_safe_ident(method)}({', '.join(args)})"

    def _emit_map_method(
        self, method: str, recv: str, args: list[str],
    ) -> str:
        """Maps a Capa Map method to a Python construct.

        Map is represented as a Python ``dict``. ``get`` returns an
        ``Option`` (Some/None_) - we emit a ternary expression.
        ``set`` is mutation - we use ``__setitem__`` to keep the
        method as an expression (returns None).
        """
        if method == "length":
            return f"len({recv})"
        if method == "contains_key":
            return f"({args[0]} in {recv})"
        if method == "get":
            # Option<V>: Some(m[k]) if key exists, None_ otherwise.
            return f"(Some({recv}[{args[0]}]) if {args[0]} in {recv} else None_)"
        if method == "set":
            # Mutation. Assignment in Python is not an expression, but
            # ``dict.__setitem__`` is. Returns None.
            return f"{recv}.__setitem__({args[0]}, {args[1]})"
        if method == "keys":
            return f"CapaList({recv}.keys())"
        if method == "values":
            return f"CapaList({recv}.values())"
        if method == "is_empty":
            return f"(len({recv}) == 0)"
        return f"{recv}.{_safe_ident(method)}({', '.join(args)})"

    def _emit_set_method(
        self, method: str, recv: str, args: list[str],
    ) -> str:
        """Maps a Capa Set method to a Python construct.

        Set is represented as a Python ``set``. ``add`` and ``remove``
        exist with the same names.
        """
        if method == "length":
            return f"len({recv})"
        if method == "contains":
            return f"({args[0]} in {recv})"
        if method == "add":
            return f"{recv}.add({args[0]})"
        if method == "remove":
            return f"{recv}.discard({args[0]})"  # discard is safe (does not raise)
        if method == "to_list":
            return f"CapaList({recv})"
        if method == "is_empty":
            return f"(len({recv}) == 0)"
        return f"{recv}.{_safe_ident(method)}({', '.join(args)})"

    def _emit_call(self, e: A.Call) -> str:
        # Special case: callee is an IDENT that is a variant with payload.
        # Already handled naturally - `Some(x)` in Capa becomes `Some(x)`
        # in Python because Some is a class.
        # Builtin collection-creation functions: emit Python literals.
        if isinstance(e.callee, A.Ident):
            if e.callee.name == "new_map" and not e.args:
                return "{}"
            if e.callee.name == "new_set" and not e.args:
                return "set()"
        callee = self._emit_call_callee(e.callee)
        args = self._emit_call_arg_list(e.args, e.arg_names)
        return f"{callee}({args})"

    def _emit_call_arg_list(
        self, args: list[A.Expr], arg_names: list,
    ) -> str:
        """Render a call argument list, including any named arguments
        as Python keyword arguments (``name=value``). Capa parameter
        names are mapped through ``_safe_ident`` because they may
        collide with Python reserved words.
        """
        parts: list[str] = []
        for i, a in enumerate(args):
            name = arg_names[i] if i < len(arg_names) else None
            code = self._emit_expr(a)
            if name is None:
                parts.append(code)
            else:
                parts.append(f"{_safe_ident(name)}={code}")
        return ", ".join(parts)

    def _emit_call_callee(self, e: A.Expr) -> str:
        # When emitting a Call, the callee is a concrete call;
        # we avoid the "constant variant = `()`" heuristic here.
        if isinstance(e, A.Ident):
            return _safe_ident(e.name)
        if isinstance(e, A.FieldAccess):
            recv = self._emit_expr(e.receiver)
            return f"{recv}.{_safe_ident(e.field_name)}"
        return self._emit_expr(e)

    def _emit_try(self, e: A.Try) -> str:
        """``?`` operator: propagates ``Err`` early by returning.

        Strategy: generates code that evaluates the expression into a
        temporary, and if it is Err, returns it. Otherwise, returns the
        ``.value``.

        To do this with expressions, we would use a walrus expression
        inside a lambda trick. But that is fragile - we prefer the `?`
        to appear in statements where we can *hoist* the temporary onto
        a previous line.

        For v1, we use an approach that requires co-writing with the
        statement emitter: emit `(tmp := <expr>).value if isinstance(tmp, Ok) else (return tmp)`
        - but Python does not allow return in an expression.

        Pragmatic solution: we emit a call to `_capa_try` that raises a
        special exception; the caller (the function where the ? appears)
        must catch it. This loosens the "pure early return" semantics
        but works transparently.
        """
        # For v1, we use a helper that raises a special exception
        # and is caught at the function boundary. Not ideal
        # performance-wise, but correct.
        inner = self._emit_expr(e.expr)
        return f"_capa_try({inner})"

    def _emit_interpolated_string(self, e: A.InterpolatedString) -> str:
        """Emits a string with interpolations as a Python f-string.

        Each Expr part is processed via ``_emit_expr`` (with correct
        type dispatch, e.g., ``s.length()`` -> ``len(s)``). Literal
        text between interpolations is escaped so it does not interfere
        with f-string syntax.
        """
        parts: list[str] = []
        for part in e.parts:
            if isinstance(part, str):
                # Escape f-string special characters: { } and \
                escaped = (
                    part.replace("\\", "\\\\")
                    .replace('"', '\\"')
                    .replace("{", "{{")
                    .replace("}", "}}")
                    .replace("\n", "\\n")
                    .replace("\t", "\\t")
                    .replace("\r", "\\r")
                )
                parts.append(escaped)
            else:
                expr_code = self._emit_expr(part)
                parts.append("{" + expr_code + "}")
        return 'f"' + "".join(parts) + '"'

    def _emit_string_lit(self, value: str) -> str:
        """Converts a Capa literal to Python.

        If the literal contains ``${expr}``, emits an f-string.
        Otherwise, emits with ``repr``.

        ``$$`` escapes a literal ``$``.
        """
        if "${" not in value:
            return repr(value)
        # Build an f-string. We must escape literal { and }.
        parts: list[str] = []
        i = 0
        while i < len(value):
            c = value[i]
            if c == "$" and i + 1 < len(value) and value[i + 1] == "$":
                parts.append("$")
                i += 2
                continue
            if c == "$" and i + 1 < len(value) and value[i + 1] == "{":
                # Find the matching `}`.
                depth = 1
                j = i + 2
                while j < len(value) and depth > 0:
                    if value[j] == "{":
                        depth += 1
                    elif value[j] == "}":
                        depth -= 1
                    if depth > 0:
                        j += 1
                if depth != 0:
                    raise TranspilerError(
                        f"unterminated interpolation in string literal: {value!r}"
                    )
                expr_text = value[i + 2 : j]
                parts.append("{" + expr_text + "}")
                i = j + 1
                continue
            if c == "{":
                parts.append("{{")
                i += 1
                continue
            if c == "}":
                parts.append("}}")
                i += 1
                continue
            parts.append(c)
            i += 1
        body = "".join(parts)
        # Escape backslashes and quotes for safe f-string repr.
        # The simplest way: emit as f"..." with double quotes, escaping
        # only `\` and `"`.
        escaped = body.replace("\\", "\\\\").replace('"', '\\"')
        # Literal newlines must become \n to fit in a single-line f-string.
        escaped = escaped.replace("\n", "\\n").replace("\t", "\\t")
        return f'f"{escaped}"'


# ===========================================================
# Injected runtime helper (for `?`)
# ===========================================================

_TRY_HELPER = '''
class _CapaTryEarlyReturn(Exception):
    """Internal exception used by the ? operator to propagate Err.

    The _capa_run wrapper catches it at each function's boundary and
    converts it back into an Err return. The Capa programmer never sees
    this exception.
    """
    def __init__(self, err):
        self.err = err

def _capa_try(result):
    if isinstance(result, Err):
        raise _CapaTryEarlyReturn(result)
    if isinstance(result, Ok):
        return result.value
    raise RuntimeError(f"`?` applied to non-Result value: {result!r}")

def _capa_wrap(fn):
    """Decorator that catches _CapaTryEarlyReturn and returns the
    corresponding Err. Applied by the transpiler to functions that use `?`.
    """
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except _CapaTryEarlyReturn as e:
            return e.err
    wrapper.__name__ = getattr(fn, "__name__", "wrapper")
    return wrapper
'''


def _uses_try(node) -> bool:
    """Determines whether an AST subtree contains any Try expression.

    Recursively visits the subtree. Does not cross function boundaries
    (a nested fun with ? does not force the outer fun to have the
    decorator). In Capa v1 there are no nested functions, but the rule
    is here just in case.
    """
    from . import capa_ast as A

    if isinstance(node, A.Try):
        return True
    if isinstance(node, (A.FunDecl,)):
        return False  # function boundary
    if isinstance(node, list):
        return any(_uses_try(x) for x in node)
    if hasattr(node, "__dataclass_fields__"):
        for f in node.__dataclass_fields__:
            if f == "pos":
                continue
            v = getattr(node, f)
            if _uses_try(v):
                return True
    if isinstance(node, tuple):
        return any(_uses_try(x) for x in node)
    return False


def transpile(
    module: A.Module,
    filename: str = "<input>",
    types: Optional[dict[int, Ty]] = None,
) -> str:
    """Transpiles a Capa Module to a Python source string.

    The output includes the prelude (runtime imports) and the helper
    for `?`. If ``types`` is passed (from AnalyzeResult), it is used
    for type-aware dispatch on method calls.
    """
    t = Transpiler(filename=filename, types=types)
    code = t.transpile(module)
    # Insert the `?` helper right after the prelude. It is ugly but
    # simple; a future version would emit everything via structured blocks.
    lines = code.split("\n")
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("from capa.runtime"):
            # Find the closing of the import (closing parenthesis).
            j = i
            while j < len(lines) and ")" not in lines[j]:
                j += 1
            insert_at = j + 1
            break
    if insert_at == 0:
        insert_at = len(lines)
    new_lines = lines[:insert_at] + _TRY_HELPER.split("\n") + lines[insert_at:]
    return "\n".join(new_lines)
