"""Transpiler from Capa to Python 3.12+.

Strategy: walk the AST after semantic analysis, emitting Python code
line by line through an ``Emitter`` that handles indentation automatically.
The output is intended to be executed by a Python 3.10 or later
interpreter (for match/case).

Main mappings:

- Functions and methods: Python ``def`` without type annotations (simpler
  and avoids issues with generic types / capabilities whose exact
  signature does not always have an equivalent in ``typing``).
- ``let`` and ``var``: indistinguishable in Python, both emit ``x = expr``.
  The immutability of ``let`` was verified statically by the analyzer.
- ``type T { ... }`` (struct): ``@dataclass`` with the fields.
- ``type T = A | B(P) | ...`` (sum): each variant is a class. For
  variants with a payload, it is a dataclass with a single ``value`` field.
  The type name becomes a union (not emitted, Capa does not need it at
  runtime, and Python does not require it).
- ``trait``: abstract ABC with abstract methods (informative). The impls
  generate concrete subclasses.
- ``impl T``: methods added as class functions.
- ``impl Trait for T``: class T inherits from the corresponding trait.
- ``match``: Python ``match/case``.
- ``?`` (try): local expansion with ``if isinstance(_t, Err): return _t``.
- Strings with ``${expr}``: translated to f-strings; ``$$`` escapes ``$``.
- Constant variants (``Red``): call ``Red()`` (instance).
- Capabilities and types imported from the runtime stdlib: a single
  ``from capa.runtime import *`` is emitted at the top of the generated file.

The actual emission logic is split across four mixins:

- :mod:`._items` - top-level declarations and the ``main`` bootstrap.
- :mod:`._statements` - statements and patterns (l-value + match).
- :mod:`._expressions` - expression lowering, including ``?``,
  ``match`` in expression position, and string interpolation.
- :mod:`._methods` - type-specific dispatch for ``String`` / ``Map`` /
  ``Set`` method calls.

Known limitations (v1):

- No optimizations: the output is reasonably readable but is not
  "idiomatic Python", it is Python that closely mirrors the Capa
  structure.
- No tail call detection.
- ``self`` in methods is translated directly; Capa "self" and Python
  "self" align naturally.
- The ``?`` operator requires the enclosing function to return ``Result``.
  If it does not, the generated code will produce an early return of an
  Err, useful as a runtime diagnostic, but not detected at transpilation
  time in v1.
"""

from __future__ import annotations

from typing import Optional

from .. import capa_ast as A
from ..tokens import Pos
from ..typesys import Ty

from ._expressions import _ExpressionsMixin
from ._items import _ItemsMixin
from ._methods import _MethodsMixin
from ._statements import _StatementsMixin


# ===========================================================
# Header of the generated file
# ===========================================================

_PRELUDE = '''\
# Generated by capa transpiler. Do not edit by hand.
# Generated from: {filename}

from __future__ import annotations
from dataclasses import dataclass, field
from capa.runtime import (
    Ok, Err, Result, Some, None_, Option, IoError,
    Stdio, Fs, Env, Clock, Random, Net, Proc, Db, Unsafe,
    CapaList, CapaRange, CapaSet, _NoneType,
    parse_int, parse_float,
    to_float, to_int,
    panic,
    declassify,
    py_import, py_invoke,
    JNull, JBool, JNum, JStr, JArr, JObj, JsonValue,
    parse_json, to_json,
    _capa_iadd, _capa_isub, _capa_imul, _capa_idiv, _capa_shl, _capa_shr,
    _capa_list_get, _capa_substring, _capa_chr,
)
'''


class TranspilerError(Exception):
    """Transpiler error (an unsupported transpilation case)."""
    pass


# ===========================================================
# Emitter: handles indentation and lines
# ===========================================================


class Emitter:
    """Accumulator of output lines with automatic indentation."""

    def __init__(self, indent_unit: str = "    "):
        self.lines: list[str] = []
        self._indent = 0
        self._unit = indent_unit

    def write(self, line: str) -> None:
        if line == "":
            self.lines.append("")
        else:
            self.lines.append(self._unit * self._indent + line)

    def blank(self) -> None:
        # Only add a blank line if the last one is not already blank.
        if self.lines and self.lines[-1] != "":
            self.lines.append("")

    def indent(self) -> None:
        self._indent += 1

    def dedent(self) -> None:
        self._indent -= 1
        assert self._indent >= 0

    def current_line(self) -> int:
        # 1-based number of the most recently emitted physical line.
        # The next ``write`` lands on ``current_line() + 1``. Counts
        # embedded newlines because some entries (notably the prelude)
        # are appended as a single multi-line string rather than one
        # call to ``write`` per line.
        return sum(entry.count("\n") + 1 for entry in self.lines)

    def get(self) -> str:
        # Ensures the file ends with a newline and has no trailing
        # blank lines.
        text = "\n".join(self.lines).rstrip() + "\n"
        return text


# ===========================================================
# Transpiler
# ===========================================================


# Capa operators -> Python (most are the same, a few need mapping).
# Bitwise / shift ops are pass-through: Python's ``& | ^ << >>`` on
# ``int`` match Capa's Int semantics, including signed arbitrary-
# precision arithmetic. The Wasm side is fixed-width i64, so for
# values that overflow i64 the two backends diverge by overflow
# semantics (Wasm wraps mod 2^64, Python doesn't), but every Capa
# Int the analyzer types is conceptually 64-bit, so a well-typed
# program stays in range.
_BINOP_MAP = {
    "+": "+",
    "-": "-",
    "*": "*",
    "/": "/",
    "%": "%",
    "&": "&",
    "|": "|",
    "^": "^",
    "<<": "<<",
    ">>": ">>",
    "==": "==",
    "!=": "!=",
    "<": "<",
    "<=": "<=",
    ">": ">",
    ">=": ">=",
    "and": "and",
    "or": "or",
}

_UNARY_MAP = {
    "-": "-",
    "not": "not ",  # space - `not` is a word
}


# Reserved Python identifiers (relevant subset to avoid collisions
# with Capa names when we emit Python).
_PY_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}


def _safe_ident(name: str) -> str:
    """Suffix names that collide with Python keywords."""
    if name in _PY_KEYWORDS:
        return name + "_"
    return name


class Transpiler(
    _ItemsMixin,
    _StatementsMixin,
    _ExpressionsMixin,
    _MethodsMixin,
):
    """Transpiles a Capa AST to Python 3.10+.

    Can optionally receive ``types`` (mapping ``id(expr) -> Ty``)
    from AnalyzeResult, which allows emitting more precise code for
    method calls on specific types (e.g., String, List).
    """

    def __init__(
        self,
        filename: str = "<input>",
        types: Optional[dict[int, Ty]] = None,
        bindings: Optional[dict[int, "object"]] = None,
    ):
        self.filename = filename
        self.em = Emitter()
        # Counter for unique temporary names (e.g., for `?`).
        self._tmp_counter = 0
        # Stack for "are we inside a function that can propagate errors?".
        # Not used for checking (that is the checker's job), but to
        # generate good code for ?.
        self._fun_stack: list[str] = []
        # Type mapping from the analyzer (optional, but needed for
        # type-aware dispatch in method calls - e.g., String methods
        # that must map to distinct Python functions).
        self.types: dict[int, Ty] = types or {}
        # Ident-binding map from the analyzer (optional, but needed
        # so the ident emitter can tell a payload-less variant
        # (``Red`` -> ``Red()``) from an UPPERCASE constant
        # (``INFO`` -> ``INFO``). When absent, falls back to the
        # uppercase-is-variant heuristic; that heuristic is wrong
        # for all-caps constants and the bindings map is the proper
        # fix.
        self.bindings: dict[int, "object"] = bindings or {}
        # Set of type names with a ``fun to_string(self) -> String``
        # declared in an impl block. The interpolated-string emitter
        # consults this to route ``${value}`` of such a type through
        # ``{value.to_string()}`` (Display protocol) instead of the
        # default ``{value}`` which falls through to dataclass repr.
        # Populated in ``transpile()`` once the module is in hand.
        self._display_types: set[str] = set()
        # Statement-level source map: generated Python line (1-based,
        # as it sits in ``self.em.lines`` before the ``?`` helper is
        # spliced in) -> originating Capa ``Pos``. Populated by
        # ``_mark`` at each statement-emit boundary; the module-level
        # ``transpile`` rebases these onto the final file's numbering.
        self.line_map: dict[int, Pos] = {}
        # REPL module-scope mode. When the REPL executes a turn's new
        # statements at Python module scope (not inside a function), a
        # ``?`` cannot lower to the usual ``return``-hoist: there is no
        # enclosing function to return from. With this flag set, the
        # statement-position ``?`` is routed through the always-correct
        # ``_capa_try`` expression path instead (it raises
        # ``_CapaTryEarlyReturn``, which the REPL catches at the exec
        # boundary). Off everywhere except the REPL's incremental
        # executor; see :func:`capa.repl`.
        self.repl_toplevel: bool = False

    def _mark(self, node) -> None:
        """Record the Capa ``Pos`` of ``node`` against the Python line
        the next ``write`` will occupy. Called at the top of each
        statement emit so a runtime traceback frame can be traced back
        to the Capa statement that produced it."""
        self.line_map[self.em.current_line() + 1] = node.pos

    def transpile(self, module: A.Module) -> str:
        self.em.lines.append(_PRELUDE.format(filename=self.filename).rstrip())
        self.em.blank()

        # Pre-pass: discover every (type_name) with a
        # ``fun to_string(self) -> String`` declared in an impl
        # block. Mirrors the Wasm emitter's `_method_table` lookup
        # so ${struct} interpolation routes through the user's
        # to_string() on both backends consistently.
        for item in module.items:
            if not isinstance(item, A.ImplBlock):
                continue
            for method in item.methods:
                if method.name != "to_string":
                    continue
                non_self = [p for p in method.params if p.name != "self"]
                if non_self:
                    continue
                ret = getattr(method, "return_type", None)
                if (
                    ret is not None
                    and isinstance(ret, A.TypeName)
                    and ret.name == "String"
                ):
                    self._display_types.add(item.type_name)

        # First pass: handle all imports, top-level consts and type decls.
        for item in module.items:
            self._emit_item(item)
            self.em.blank()

        # Detect if there is a `main` and generate the bootstrap.
        main_decl = next(
            (
                it for it in module.items
                if isinstance(it, A.FunDecl) and it.name == "main"
            ),
            None,
        )
        if main_decl is not None:
            self._emit_main_bootstrap(main_decl)

        return self.em.get()


# ===========================================================
# Injected runtime helper (for `?`)
# ===========================================================

_TRY_HELPER = '''
class _CapaTryEarlyReturn(Exception):
    """Internal exception used by the ? operator to propagate Err
    or None_ from an expression context. The @_capa_wrap decorator
    catches it at the function boundary and converts it back into
    the matching return value. Capa programmers never see it.

    Only used when ? appears in an expression position (sub-expr of
    a BinOp, inside a call argument, etc.). When ? sits directly as
    the value of a let / return / expression statement, the
    transpiler hoists the check inline and the exception path is
    not taken.
    """
    def __init__(self, value):
        self.value = value

def _capa_try(value):
    """Runtime ? operator for the expression-position case. Returns
    the unwrapped payload for Ok / Some, raises an internal exception
    for Err / None_ (caught by @_capa_wrap at the function boundary).
    """
    if isinstance(value, Err):
        raise _CapaTryEarlyReturn(value)
    if isinstance(value, Ok):
        return value.value
    if value is None_:
        raise _CapaTryEarlyReturn(value)
    if isinstance(value, Some):
        return value.value
    raise RuntimeError(
        f"`?` applied to a value that is not Result or Option: {value!r}",
    )

def _capa_wrap(fn):
    """Decorator that catches _CapaTryEarlyReturn and returns the
    propagated Err / None_. Applied by the transpiler to functions
    where at least one ? sits in an expression position that the
    inline hoist could not handle. Functions whose ? uses are all
    hoisted skip the decorator entirely.
    """
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except _CapaTryEarlyReturn as e:
            return e.value
    wrapper.__name__ = getattr(fn, "__name__", "wrapper")
    return wrapper
'''


def _uses_try(node) -> bool:
    """Determines whether an AST subtree contains any Try expression.

    Recursively visits the subtree. Stops at function boundaries:
    ``FunDecl`` and ``LambdaExpr``. A nested function or lambda with
    ``?`` does not force the outer function to have the decorator --
    the inner one gets its own decorator at its own boundary, and the
    exception never escapes past it.
    """
    if isinstance(node, A.Try):
        return True
    if isinstance(node, (A.FunDecl, A.LambdaExpr)):
        return False  # function boundary
    if isinstance(node, list):
        return any(_uses_try(x) for x in node)
    if hasattr(node, "__dataclass_fields__"):
        for f in node.__dataclass_fields__:
            if f == "pos":
                continue
            v = getattr(node, f)
            if _uses_try(v):
                return True
    if isinstance(node, tuple):
        return any(_uses_try(x) for x in node)
    return False


def _uses_exception_try(node) -> bool:
    """Whether the function body needs the ``@_capa_wrap`` decorator.

    The decorator is the soundness safety net for ``?``: it catches
    the internal ``_CapaTryEarlyReturn`` exception that ``_capa_try``
    raises on the Err / None_ path. The transpiler additionally
    *hoists* ``?`` inline at known statement-top positions
    (``LetStmt``, ``VarStmt``, ``AssignStmt``, ``ReturnStmt``,
    ``ExprStmt``) so the common cases avoid the exception cost; but
    those hoists are an optimisation, not a soundness requirement.

    For correctness we simply emit the decorator whenever there is
    any ``?`` anywhere in the function body. The cost is one Python
    call frame per invocation of a function-with-?, which is
    negligible; the alternative -- enumerating every position the
    transpiler hoists and keeping the two lists in sync -- is the
    fragile pattern that previously left ``var x = foo()?``,
    ``x = foo()?``, and ``x += foo()?`` raising uncaught
    ``_CapaTryEarlyReturn`` at runtime.
    """
    return _uses_try(node)


def transpile_repl(
    module: A.Module,
    new_items: list,
    new_stmts: list,
    types: Optional[dict[int, Ty]] = None,
    bindings: Optional[dict[int, "object"]] = None,
) -> str:
    """Render REPL turn code (new top-level items + new main-body
    statements) as Python for module-scope exec into the REPL's
    persistent namespace. No prelude/helper (already in the namespace).
    Statements are emitted at module scope with repl_toplevel=True so
    `?` routes through the _capa_try exception path; the REPL catches
    _CapaTryEarlyReturn at the exec boundary. Items keep normal
    function-scoped lowering (their own @_capa_wrap + return-hoist).

    The two context pre-passes that ``Transpiler.transpile`` runs over
    the whole module are repeated here over the FULL ``module`` (not
    just the new slice) so emission has the context it needs: the
    Display-protocol set (``_display_types``) and the sum-type variant
    map (``_sum_variant_names``). Without them a new ``impl`` block on
    a sum type declared in a prior turn could not find the variant
    classes to attach its methods to, and ``${value}`` interpolation
    of a prior-turn struct would miss its ``to_string()``.
    """
    t = Transpiler(filename="<repl>", types=types, bindings=bindings)

    # Pre-pass (a): Display protocol. Mirror transpile()'s loop so a
    # ${value} of a type with `fun to_string(self) -> String` routes
    # through value.to_string() instead of the dataclass repr, even
    # when that impl block was committed in an earlier turn.
    for item in module.items:
        if not isinstance(item, A.ImplBlock):
            continue
        for method in item.methods:
            if method.name != "to_string":
                continue
            non_self = [p for p in method.params if p.name != "self"]
            if non_self:
                continue
            ret = getattr(method, "return_type", None)
            if (
                ret is not None
                and isinstance(ret, A.TypeName)
                and ret.name == "String"
            ):
                t._display_types.add(item.type_name)

    # Pre-pass (b): sum-type variant names. A new impl block on a sum
    # type declared in a prior turn needs the variant class names so
    # its methods attach to the right classes.
    if not hasattr(t, "_sum_variant_names"):
        t._sum_variant_names = {}
    for item in module.items:
        if isinstance(item, A.TypeSum):
            t._sum_variant_names[item.name] = [v.name for v in item.variants]

    # New top-level items keep normal function-scoped lowering
    # (repl_toplevel stays False here).
    for item in new_items:
        t._emit_item(item)
        t.em.blank()

    # New main-body statements run at module scope: flip the flag so a
    # statement-position ? routes through _capa_try (the REPL catches
    # _CapaTryEarlyReturn at the exec boundary).
    if new_stmts:
        t.repl_toplevel = True
        for s in new_stmts:
            t._emit_stmt(s)

    return t.em.get()


def transpile(
    module: A.Module,
    filename: str = "<input>",
    types: Optional[dict[int, Ty]] = None,
    bindings: Optional[dict[int, "object"]] = None,
    out_line_map: Optional[dict[int, Pos]] = None,
) -> str:
    """Transpiles a Capa Module to a Python source string.

    The output includes the prelude (runtime imports) and the helper
    for `?`. If ``types`` is passed (from AnalyzeResult), it is used
    for type-aware dispatch on method calls. ``bindings`` (from
    AnalyzeResult) lets the emitter tell payload-less variants from
    UPPERCASE constants when both appear as bare identifiers.

    Side channel: if ``out_line_map`` is passed (a dict), it is filled
    in place with a ``python_line -> Pos`` statement-level source map
    keyed by 1-based line numbers in the *returned* string. Callers
    that do not need it pass nothing and see no change; the return
    type is always ``str``.
    """
    t = Transpiler(filename=filename, types=types, bindings=bindings)
    code = t.transpile(module)
    # Insert the `?` helper right after the prelude. It is ugly but
    # simple; a future version would emit everything via structured blocks.
    lines = code.split("\n")
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("from capa.runtime"):
            # Find the closing of the import (closing parenthesis).
            j = i
            while j < len(lines) and ")" not in lines[j]:
                j += 1
            insert_at = j + 1
            break
    if insert_at == 0:
        insert_at = len(lines)
    helper_lines = _TRY_HELPER.split("\n")
    new_lines = lines[:insert_at] + helper_lines + lines[insert_at:]
    if out_line_map is not None:
        # Rebase the transpiler's pre-splice line numbers onto the
        # final file. A line whose 1-based number L sits at list index
        # L-1; lines at index >= insert_at shift down by the helper
        # length once the helper is spliced in.
        shift = len(helper_lines)
        for py_line, pos in t.line_map.items():
            if py_line - 1 >= insert_at:
                out_line_map[py_line + shift] = pos
            else:
                out_line_map[py_line] = pos
    return "\n".join(new_lines)
