"""Transpiler from Capa to Python 3.12+.

Strategy: walk the AST after semantic analysis, emitting Python code
line by line through an ``Emitter`` that handles indentation automatically.
The output is intended to be executed by a Python 3.10 or later
interpreter (for match/case).

Main mappings:

- Functions and methods: Python ``def`` without type annotations (simpler
  and avoids issues with generic types / capabilities whose exact
  signature does not always have an equivalent in ``typing``).
- ``let`` and ``var``: indistinguishable in Python, both emit ``x = expr``.
  The immutability of ``let`` was verified statically by the analyzer.
- ``type T { ... }`` (struct): ``@dataclass`` with the fields.
- ``type T = A | B(P) | ...`` (sum): each variant is a class. For
  variants with a payload, it is a dataclass with a single ``value`` field.
  The type name becomes a union (not emitted, Capa does not need it at
  runtime, and Python does not require it).
- ``trait``: abstract ABC with abstract methods (informative). The impls
  generate concrete subclasses.
- ``impl T``: methods added as class functions.
- ``impl Trait for T``: class T inherits from the corresponding trait.
- ``match``: Python ``match/case``.
- ``?`` (try): local expansion with ``if isinstance(_t, Err): return _t``.
- Strings with ``${expr}``: translated to f-strings; ``$$`` escapes ``$``.
- Constant variants (``Red``): call ``Red()`` (instance).
- Capabilities and types imported from the runtime stdlib: a single
  ``from capa.runtime import *`` is emitted at the top of the generated file.

The actual emission logic is split across four mixins:

- :mod:`._items` - top-level declarations and the ``main`` bootstrap.
- :mod:`._statements` - statements and patterns (l-value + match).
- :mod:`._expressions` - expression lowering, including ``?``,
  ``match`` in expression position, and string interpolation.
- :mod:`._methods` - type-specific dispatch for ``String`` / ``Map`` /
  ``Set`` method calls.

Known limitations (v1):

- No optimizations: the output is reasonably readable but is not
  "idiomatic Python", it is Python that closely mirrors the Capa
  structure.
- No tail call detection.
- ``self`` in methods is translated directly; Capa "self" and Python
  "self" align naturally.
- The ``?`` operator requires the enclosing function to return ``Result``.
  If it does not, the generated code will produce an early return of an
  Err, useful as a runtime diagnostic, but not detected at transpilation
  time in v1.
"""

from __future__ import annotations

from typing import Optional

from .. import capa_ast as A
from ..typesys import Ty

from ._expressions import _ExpressionsMixin
from ._items import _ItemsMixin
from ._methods import _MethodsMixin
from ._statements import _StatementsMixin


# ===========================================================
# Header of the generated file
# ===========================================================

_PRELUDE = '''\
# Generated by capa transpiler. Do not edit by hand.
# Generated from: {filename}

from __future__ import annotations
from dataclasses import dataclass, field
from capa.runtime import (
    Ok, Err, Result, Some, None_, Option, IoError,
    Stdio, Fs, Env, Clock, Random, Net, Proc, Db, Unsafe,
    CapaList, _NoneType,
    parse_int, parse_float,
    to_float, to_int,
    py_import, py_invoke,
    JNull, JBool, JNum, JStr, JArr, JObj, JsonValue,
    parse_json, to_json,
)
'''


class TranspilerError(Exception):
    """Transpiler error (an unsupported transpilation case)."""
    pass


# ===========================================================
# Emitter: handles indentation and lines
# ===========================================================


class Emitter:
    """Accumulator of output lines with automatic indentation."""

    def __init__(self, indent_unit: str = "    "):
        self.lines: list[str] = []
        self._indent = 0
        self._unit = indent_unit

    def write(self, line: str) -> None:
        if line == "":
            self.lines.append("")
        else:
            self.lines.append(self._unit * self._indent + line)

    def blank(self) -> None:
        # Only add a blank line if the last one is not already blank.
        if self.lines and self.lines[-1] != "":
            self.lines.append("")

    def indent(self) -> None:
        self._indent += 1

    def dedent(self) -> None:
        self._indent -= 1
        assert self._indent >= 0

    def get(self) -> str:
        # Ensures the file ends with a newline and has no trailing
        # blank lines.
        text = "\n".join(self.lines).rstrip() + "\n"
        return text


# ===========================================================
# Transpiler
# ===========================================================


# Capa operators -> Python (most are the same, a few need mapping).
_BINOP_MAP = {
    "+": "+",
    "-": "-",
    "*": "*",
    "/": "/",
    "%": "%",
    "==": "==",
    "!=": "!=",
    "<": "<",
    "<=": "<=",
    ">": ">",
    ">=": ">=",
    "and": "and",
    "or": "or",
}

_UNARY_MAP = {
    "-": "-",
    "not": "not ",  # space - `not` is a word
}


# Reserved Python identifiers (relevant subset to avoid collisions
# with Capa names when we emit Python).
_PY_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}


def _safe_ident(name: str) -> str:
    """Suffix names that collide with Python keywords."""
    if name in _PY_KEYWORDS:
        return name + "_"
    return name


class Transpiler(
    _ItemsMixin,
    _StatementsMixin,
    _ExpressionsMixin,
    _MethodsMixin,
):
    """Transpiles a Capa AST to Python 3.10+.

    Can optionally receive ``types`` (mapping ``id(expr) -> Ty``)
    from AnalyzeResult, which allows emitting more precise code for
    method calls on specific types (e.g., String, List).
    """

    def __init__(
        self,
        filename: str = "<input>",
        types: Optional[dict[int, Ty]] = None,
    ):
        self.filename = filename
        self.em = Emitter()
        # Counter for unique temporary names (e.g., for `?`).
        self._tmp_counter = 0
        # Stack for "are we inside a function that can propagate errors?".
        # Not used for checking (that is the checker's job), but to
        # generate good code for ?.
        self._fun_stack: list[str] = []
        # Type mapping from the analyzer (optional, but needed for
        # type-aware dispatch in method calls - e.g., String methods
        # that must map to distinct Python functions).
        self.types: dict[int, Ty] = types or {}

    def transpile(self, module: A.Module) -> str:
        self.em.lines.append(_PRELUDE.format(filename=self.filename).rstrip())
        self.em.blank()

        # First pass: handle all imports, top-level consts and type decls.
        for item in module.items:
            self._emit_item(item)
            self.em.blank()

        # Detect if there is a `main` and generate the bootstrap.
        main_decl = next(
            (
                it for it in module.items
                if isinstance(it, A.FunDecl) and it.name == "main"
            ),
            None,
        )
        if main_decl is not None:
            self._emit_main_bootstrap(main_decl)

        return self.em.get()


# ===========================================================
# Injected runtime helper (for `?`)
# ===========================================================

_TRY_HELPER = '''
class _CapaTryEarlyReturn(Exception):
    """Internal exception used by the ? operator to propagate Err.

    The _capa_run wrapper catches it at each function's boundary and
    converts it back into an Err return. The Capa programmer never sees
    this exception.
    """
    def __init__(self, err):
        self.err = err

def _capa_try(result):
    if isinstance(result, Err):
        raise _CapaTryEarlyReturn(result)
    if isinstance(result, Ok):
        return result.value
    raise RuntimeError(f"`?` applied to non-Result value: {result!r}")

def _capa_wrap(fn):
    """Decorator that catches _CapaTryEarlyReturn and returns the
    corresponding Err. Applied by the transpiler to functions that use `?`.
    """
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except _CapaTryEarlyReturn as e:
            return e.err
    wrapper.__name__ = getattr(fn, "__name__", "wrapper")
    return wrapper
'''


def _uses_try(node) -> bool:
    """Determines whether an AST subtree contains any Try expression.

    Recursively visits the subtree. Does not cross function boundaries
    (a nested fun with ? does not force the outer fun to have the
    decorator). In Capa v1 there are no nested functions, but the rule
    is here just in case.
    """
    if isinstance(node, A.Try):
        return True
    if isinstance(node, (A.FunDecl,)):
        return False  # function boundary
    if isinstance(node, list):
        return any(_uses_try(x) for x in node)
    if hasattr(node, "__dataclass_fields__"):
        for f in node.__dataclass_fields__:
            if f == "pos":
                continue
            v = getattr(node, f)
            if _uses_try(v):
                return True
    if isinstance(node, tuple):
        return any(_uses_try(x) for x in node)
    return False


def transpile(
    module: A.Module,
    filename: str = "<input>",
    types: Optional[dict[int, Ty]] = None,
) -> str:
    """Transpiles a Capa Module to a Python source string.

    The output includes the prelude (runtime imports) and the helper
    for `?`. If ``types`` is passed (from AnalyzeResult), it is used
    for type-aware dispatch on method calls.
    """
    t = Transpiler(filename=filename, types=types)
    code = t.transpile(module)
    # Insert the `?` helper right after the prelude. It is ugly but
    # simple; a future version would emit everything via structured blocks.
    lines = code.split("\n")
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("from capa.runtime"):
            # Find the closing of the import (closing parenthesis).
            j = i
            while j < len(lines) and ")" not in lines[j]:
                j += 1
            insert_at = j + 1
            break
    if insert_at == 0:
        insert_at = len(lines)
    new_lines = lines[:insert_at] + _TRY_HELPER.split("\n") + lines[insert_at:]
    return "\n".join(new_lines)
